### PR TITLE
Include changes for release notes references

### PR DESCRIPTION
**Pull request by bganapa**

### CODE REVIEW

**Review by mattbriggs — CHANGES_REQUESTED** [review]
Hi Bala, there is a typo in this. But can you add the top level release notes to this topic rather than pointing to the github repo?

Here is the text:

The AzureStack release updates the capabilities in the Azs.Compute.Admin module. The update adds new modules for working with Azure Container Registry on Azure Stack Hub: Azs.ContainerRegistry.Admin and Azs.ContainerService.Admin. Also, the Admin modules now have a dependency on the Az. Resources module version 0.12.0. For details on the changes in this update, see [the AzureStack module change log](https://github.com/Azure/azurestack-powershell/blob/release-2108/src/changelog.md)

**Comment by mattbriggs** [comment]
@mikefrobbins Thanks for the heads up!

**Comment by bganapa** [comment]
> Hi Bala, there is a typo in this. But can you add the top level release notes to this topic rather than pointing to the github repo?
> 
> Here is the text:
> 
> The AzureStack release updates the capabilities in the Azs.Compute.Admin module. The update adds new modules for working with Azure Container Registry on Azure Stack Hub: Azs.ContainerRegistry.Admin and Azs.ContainerService.Admin. Also, the Admin modules now have a dependency on the Az. Resources module version 0.12.0. For details on the changes in this update, see [the AzureStack module change log](https://github.com/Azure/azurestack-powershell/blob/release-2108/src/changelog.md)

Thanks @mattbriggs . I have addressed the review comments

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Pull request merged**
