### PR TITLE
Resolving merge conflicts and adding 2.5.0

### PR DESCRIPTION
**Pull request by sijuman**
@bganapa @mattbriggs

### CODE REVIEW

**Comment by sijuman** [comment]
@sptramer Hi Stephen, I haven't touched either of those files. Can you help as to why the error is occurring?

**Comment by sptramer** [comment]
@sijuman @bganapa @mattbriggs Please make sure that the azurermps-2.5.0 moniker exists and is correctly enabled. Once it is, leave a comment and this PR can be merged.

**Comment by sijuman** [comment]
The moniker has been enabled and set to live. @sptramer

**Comment by sptramer** [comment]
Close/reopen to try and force another build. It looks like there may still be a moniker problem @sijuman

**Comment by sptramer** [comment]
@sijuman Indeed, the azurermps-2.5.0 moniker does not exist.

image

**Comment by sijuman** [comment]
@sptramer I was told that the correct moniker has been created and set to live. I tagged you on email thread as well just in case. Please let me know.

**Pull request merged**
