### PR TITLE
fix formatting, fix the code, fix the comments, remove spaces

### PR DESCRIPTION
**Pull request by cblackuk**
Trying to make this document a lot more useful and up to date with the current modules and documentation that already exists in Azure Stack docs.

I came across this issue when I was doing some troubleshooting for this issue -> https://github.com/Azure/azure-powershell/issues/8847

I hope that helps.

@bganapa can you take a look at it please? :-)

### CODE REVIEW

**Comment by cblackuk** [comment]
@bganapa  can we merge please?

**Comment by bganapa** [comment]
@BaileyLawson  This should have been auto merged?

**Comment by cblackuk** [comment]
@bganapa  you would have to #sign-off it I think?

**Comment by BaileyLawson** [comment]
@bganapa Doesn't seem to be working at the moment, could you merge it for me please?

**Comment by mattbriggs** [comment]
@bganapa Looks like @sijuman is the author. @sijuman can you review? Thanks! Matt

**Pull request merged**
