### PR TITLE
Update release-notes-azureps.md

### PR DESCRIPTION
**Pull request by john-par**
Updates related to [User Story 1658959](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1658959).

### CODE REVIEW

**Comment by john-par** [comment]
This PR is a minor change for a LOC fix.

#sign-off

**Comment by john-par** [comment]
@huypub, hi, my name is John. I'm a Technical Writer working on [User Story 1658959](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1658959).

I was wondering if you could review this PR for me and merge the content if you're comfortable with it?

**Comment by huypub** [comment]
@john-par, I am not the right person for merging this kind of PR. As I know, you may contact the following people for help: Stephen.Tramer@microsoft.com; mikki@microsoft.com; routlaw@microsoft.com

**Comment by john-par** [comment]
Thank you @huypub. Sorry for the misunerstanding.

**Comment by john-par** [comment]
@sdwheeler I'm contacting you because you have merged recent PRs in this repo. I was wondering if you could take a look at this PR and let me know if it looks okay or if there's anything you'd like me to change.

I don’t mean to push, but I want to make sure that I can close the associated [user story](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1658959) in a timely fashion so the Translator can continue their work.

**Comment by sdwheeler** [comment]
@john-par Please fix warnings and suggestions.

**Comment by john-par** [comment]
@sdwheeler sorry for not responding to your email yesterday. I have cleared all of the build warnings related to `http` VS `https`. I can't fix the remaining warning or suggestion. Reasons:

* **Warning**: I can't fix this one because I've never encountered an [`includes` MD file](https://github.com/john-par/azure-docs-powershell/blob/patch-1/azuresmps-4.0.0/include/sb-deprecation.md) with front matter meta data in it. I wouldn't know what `title` to add to the front matter to clear that warning. If you could suggest one, I'd be happy to add it.
* **Suggestion**: If I changed the first heading in the [release notes MD file](https://github.com/john-par/azure-docs-powershell/blob/patch-1/docs-conceptual/azps-3.2.0/release-notes-azureps.md) from an H2 to an H1, then I would be "breaking" the format of the rest of the article. I see that all of the release note headings in the file are H2. Please provide explicit permission to change the first H2 to an H1.

**Pull request merged**
