### PR TITLE
PM updates: Enable-AzRecoveryServicesBackupProtection

### PR DESCRIPTION
**Pull request by v-amallick**

### CODE REVIEW

**Comment by v-amallick** [comment]
#sign-off

**Comment by v-amallick** [comment]
#sign-off

**Comment by mikefrobbins** [comment]
@v-amallick These changes also need to be made to the [source version](https://github.com/Azure/azure-powershell/blob/main/src/RecoveryServices/RecoveryServices/help/Enable-AzRecoveryServicesBackupProtection.md).

New releases are based on the source version. Your changes will not persist in future versions unless the source version is also updated.

**Comment by v-amallick** [comment]
@mikefrobbins - Thanks for merging the PR. Will update the source article as well.

**Pull request merged**
