### PR TITLE
Backfill the migration guide for Az.Cdn

### PR DESCRIPTION
**Pull request by TracyYaoYao**
# PR Summary

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by mikefrobbins** [comment]
@TracyYaoYao When did these changes occur? The changes are targeting the migration guide for Az version 8.0.0 which was released about 16 months ago and is no longer supported. 

Has this information been added to the migration guides in the [Azure PowerShell source repo](https://github.com/Azure/azure-powershell/tree/main/documentation/migration-guides) so future migration guides will have this information?

Also, the content in this repo is versioned and I only see updates for one of the three versions of the migration guide that would need to be updated: 
[https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.2.0/migrate-az-8.0.0.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.2.0/migrate-az-8.0.0.md)
[https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.3.0/migrate-az-8.0.0.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azps-10.3.0/migrate-az-8.0.0.md)

cc:// @dcaro

**Comment by TracyYaoYao** [comment]
@mikefrobbins I am not sure about the time these changes occur. I am just onboarding for PowerShell about 6 months. But the cmdlets could be supported before Az version 8.0.0, and they are deprecated, I suppose, in Az version 8.0.0.  I know it's not supported now, but we still received several issues and cases from customers who use 8.0.0 version, they feel confused why the cmdlets deprecated but no relevant migration guide doc. So, we suppose we still need to backfill these changes, although it's not the latest supported version. 

Yes, I also created a PR to backfill the previous changes. https://github.com/Azure/azure-powershell/pull/22779

**Comment by TracyYaoYao** [comment]
Hi, @mikefrobbins  I have updated the other two docs. Could you please help to take a look at your time? Thanks.

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Pull request merged**
