### PR TITLE
Dev edits for bganapa

### PR DESCRIPTION
**Pull request by cdpark**

### CODE REVIEW

**Comment by cdpark** [comment]
@mikefrobbins I did notice that it's being deprecated in 2024, so the edits were minor. We're primarily testing to see if we can improve the page's appearance in search results by editing metadata, fixing broken links, etc. (though no fixes were necessary in this case).

**Review by bganapa — APPROVED** [review]

**Comment by cdpark** [comment]
#sign-off

**Comment by mikefrobbins** [comment]
@dcaro, Can you provide your thoughts on improving search results for AzureRM docs?

**Comment by mikefrobbins** [comment]
@cdpark Please see the [Be found in search: Page title, description, and friendly URL](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-seo-basics?branch=main#be-found-in-search-page-title-description-and-friendly-url) of the docs contribution guide for recommended title and description lengths if this article is being optimized for SEO.

**Comment by mikefrobbins** [comment]
Reverted the changes after discussing with the Azure PowerShell PM. Docs for AzureRM should not be included in any experiment that improves visibility as deprecation has been announced for it. Our goal is to move customers to the Az PowerShell module.

**Pull request merged**
