### PR TITLE
Enable Azure Stack 1.7.2

### PR DESCRIPTION
**Pull request by BaileyLawson**

### CODE REVIEW

**Comment by BaileyLawson** [comment]
@dcaro @sdwheeler Any chance you could take a look at this? The docs for Azure Stack PowerShell are currently broken and only showing 1.6.0 as the latest version instead of 1.7.2.

**Comment by sdwheeler** [comment]
@BaileyLawson  Adding a new version requires more than just editing the mapping file. It requires provisioning in the back-end for the new version. This is work that must be done by the Docs team in coordination with the Product team. That work has not been done yet. I don't know what their schedule is for releasing this documentation.

**Comment by BaileyLawson** [comment]
@sdwheeler The rest of this was done in https://github.com/MicrosoftDocs/azure-docs-powershell/pull/1067, however I missed changing this file.

**Comment by sdwheeler** [comment]
@BaileyLawson But the moniker has not been provisioned on the back-end. So none of these changes will fix your issue until that happens.

**Comment by sdwheeler** [comment]
@mattbriggs Can you help with this PR? External contributors should not be making configuration changes like this.

**Comment by mattbriggs** [comment]
@BaileyLawson and @cblackuk Thanks for your input on this. I've followed up with the Azure Stack team and we should be updated soon. #in-progress

**Comment by cblackuk** [comment]
@mattbriggs Thanks a Matt :-) hopefully we can fix it soon :-)

**Comment by sptramer** [comment]
@mattbriggs Any updates on this?

**Comment by mattbriggs** [comment]
I haven’t had a chance to sit down and follow Roberts instructions. Hope to have time tomorrow. Thanks for asking.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BaileyLawson** [comment]
Hi all, 
Any update on when this will be done? @mattbriggs @sptramer 
Thanks

**Comment by mattbriggs** [comment]
@BaileyLawson (cc @cblackuk) Bailey, Can you close this PR and reopen? Now that we have a moniker it should be ok. However, I have some additional updates to make the repo, so if there are still issues I will resolve in my own PR. I appreciate your help. In the future can you message me, however. There are dependencies on some some backend parts that need to be coordinated.

(cc: @sptramer)

**Comment by cblackuk** [comment]
Thanks @mattbriggs 

Bailey is working on it now :-) and will do :-)

**Comment by BaileyLawson** [comment]
@mattbriggs New PR is here: https://github.com/MicrosoftDocs/azure-docs-powershell/pull/1121
In the future I'll message you first to get the backend sorted. Thanks for getting this fixed! 👍

**Pull request closed without merging**
