### PR TITLE
Update rm-groupMapping-6.13.0.json

### PR DESCRIPTION
**Pull request by JasonWHowell**
Fixing "HD Insights" --> "HDInsight"

### CODE REVIEW

**Comment by JasonWHowell** [comment]
@dend Is this a viable change?

**Comment by dendeli-msft** [comment]
@JasonWHowell should this change be done for all mapping files in place?

**Comment by JasonWHowell** [comment]
@dend if there are other files, yes, it should be changed globally I think.

**Comment by sptramer** [comment]
@JasonWHowell Yes, this needs to be changed in all mapping files related to both the Az and AzureRM modules.

**Comment by sptramer** [comment]
@sdwheeler says that this is a build artifact. That means that the metadata has to be changed in the product repo, https://github.com/azure/azure-powershell otherwise these changes will be overwritten with every new release.

**Comment by sptramer** [comment]
Here's the file you need to edit: https://github.com/Azure/azure-powershell/blob/1bcbe7b1f7a3323ac98f7754ba03eeb6b45e79f2/tools/CreateMappings_rules.json

**Pull request closed without merging**
