### PR TITLE
azurestackps-2.0.0

### PR DESCRIPTION
**Pull request by mattbriggs**

### CODE REVIEW

**Comment by mattbriggs** [comment]
@sdwheeler I am not sure why I am getting these warnings?

**Comment by mattbriggs** [comment]
#sign-off

**Comment by sdwheeler** [comment]
@mattbriggs You get those errors because that version of the content is not configured in the mapping files. You need to update [monikerMapping.json](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/mapping/monikerMapping.json) .

cc: @mikefrobbins - Mike should review and merge this for you.

**Comment by mattbriggs** [comment]
@mikefrobbins good to go. Thanks @sdwheeler for your help.

**Comment by mattbriggs** [comment]
#sign-off

**Pull request merged**
