### PR TITLE
Policheck updates - Sept. 12 | Bulk Updates

### PR DESCRIPTION
**Pull request by v-thepet**
# PR Summary

Changes:
- Cape Verde to Cabo Verde
- Turkey to Türkiye
- Whitelist to allowlist (in descriptions and text only)

Fixes the following bugs:

- [148186](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148186)
- [148190](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148190)
- [148213](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148213)
- [148182](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148182)
- [148229](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148229)
- [148250](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148250)
- [148150](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148150)
- [148204](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148204)
- [148242](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148242)
- [148170](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148170)
- [148227](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148227)
- [148184](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148184)
- [148162](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148162)
- [148199](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148199)
- [148219](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148219)
- [148244](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148244)
- [148178](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148178)
- [148175](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148175)
- [148194](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148194)
- [148171](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148171)
- [148231](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148231)
- [148222](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148222)
- [148164](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148164)
- [148247](https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/148247)

### CODE REVIEW

**Comment by mikefrobbins** [comment]
@v-thepet, 100% of these docs are autogenerated reference content. Their source resides in the [azure-powershell](https://github.com/Azure/azure-powershell) source repo. We release a new version of Azure PowerShell monthly, and these issues will reoccur each month until the source files are updated. cc:// @jasongroce

**Comment by v-thepet** [comment]
@mikefrobbins @jasongroce - Ah, sorry. I look for evidence of autogen but this repo and PRs seemed normal. I'll try to make these changes in the source repo. I don't know if you want to merge this anyway as it would be a stopgap for the month. Or I can close it. Sorry for the hassle

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Comment by v-thepet** [comment]
@mikefrobbins - Thanks for the merge. I've now made all the same changes in the source repo, PR https://github.com/Azure/azure-powershell/pull/22790

**Pull request merged**
