### PR TITLE
clarify scope of new-azdeployment

### PR DESCRIPTION
**Pull request by tfitzmac**

### CODE REVIEW

**Comment by tfitzmac** [comment]
#sign-off

**Comment by mikefrobbins** [comment]
@tfitzmac Future versions of this doc are based on the version in the AzPS source repo. I'd recommend updating it also. See [New-AzDeployment](https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/New-AzDeployment.md).

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Comment by tfitzmac** [comment]
Thanks @mikefrobbins I have an open PR in that repo too.

**Pull request merged**
